name: workflow-test

# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "build job"

  deploy-stage-job:
    runs-on: ubuntu-latest
    environment: stage
    needs: build-job

    steps:
      - run: echo "deploy stage job"
